### ISSUE TITLE
useConvexPolyhedron 에서의 에러 발생

### ISSUE THREAD

**Issue by jin-Pro** [MET-AJOU/MET-AJOU#42]
```jsx
const makeVertices = (vertices: any[]): any => vertices?.map((vertice: any) => [vertice.x, vertice.y, vertice.z]);

...

const [a] = useConvexPolyhedron(() => ({ type: "Static", args: [makeVertices(vertices), faces, makeVertices(facesNormals), makeVertices(axes), boundingSphereRadius], mass: 100, onCollide: 블락함수 ?? false }), undefined, [makeVertices(vertices), position, rotation]);

  return (
    <>
      <mesh castShadow position={position} receiveShadow geometry={geometry} material={material} />
      <mesh ref={a} />
    </>
  );

```

위 코드에서 보는 것 처럼 우리는, useConvexPolyhedron을 사용하여 args 인자에 값을 변환하여 넣어주었는데,
faceNormals에서 아래 이미지와 같은 에러가 발생하였다

<img width="679" alt="image" src="https://user-images.githubusercontent.com/70205497/161084724-3af2d129-8f0c-4c59-92a7-1a255b41b828.png">

---

위 이미지에서는 

[코드 주소](https://schteppe.github.io/cannon.js/docs/files/src_shapes_ConvexPolyhedron.js.html)

의 130번째 줄에서 알 수 있듯이, 

```jsx
var n = this.faceNormals[i] || new Vec3();  // this.faceNormals[i]
this.getFaceNormal(i,n);  // ??
n.negate(n);  // ??
this.faceNormals[i] = n; 
var vertex = this.vertices[this.faces[i][0]];  // vertex = vertices[faces[i][0]]
  if(n.dot(vertex) < 0){  // faceNormals[i].dot(vertices[faces[i][0]])  // 음수 => 에러
```

이 부분이 문제인 것 같다.

라이브러리 위치는

node_modules/cannon-es/dist/cannon-es.js 

2189번째라인
이며,

우선 로그를 주석으로 하여 실행속도를 늘렸다.

추가로, n.dot(vertex)값이 음수라면 양수로 바꾸도록 해볼 예정이다.

라이브러리를 수정하기위해서 patch-package 를 설치할 예정이다.

=> npx patch-package cannon-es

---

dot(vector) {
    return this.x * vector.x + this.y * vector.y + this.z * vector.z;
  }

**Comment by Noelsky-code** [comment]
height map 으로 해결함
